[package]
name = "loop"
description = "LOOP BANK and DUEL contracts"
version = "0.2.0"
license = "MIT"

[toolchain]
acton = "1.0.0"

[contracts.DuelEscrow]
display-name = "LOOP Duel Escrow"
src = "contracts/duel/DuelEscrow.tolk"
depends = []

[contracts.BankQueue]
display-name = "LOOP BANK FIFO Queue"
src = "contracts/bank/BankQueue.tolk"
depends = []

[test]

[fmt]
width = 100
ignore = ["wrappers"]

[scripts]
deploy-bank-emulation = "acton script scripts/deploy-bank.tolk -3 false"
deploy-bank-testnet = "acton script --net testnet scripts/deploy-bank.tolk -3 false"
deploy-bank-mainnet-emulation = "acton script scripts/deploy-bank.tolk -239 true"
deploy-bank-mainnet = "acton script --net mainnet scripts/deploy-bank.tolk -239 true"
deploy-duel-emulation = "acton script scripts/deploy-duel.tolk -3 1 false"
deploy-duel-testnet = "acton script --net testnet scripts/deploy-duel.tolk -3 0x${LOOP_DUEL_INVITE_PUBLIC_KEY} false"
deploy-duel-mainnet-emulation = "acton script scripts/deploy-duel.tolk -239 0x${LOOP_DUEL_INVITE_PUBLIC_KEY} true"
deploy-duel-mainnet = "acton script --net mainnet scripts/deploy-duel.tolk -239 0x${LOOP_DUEL_INVITE_PUBLIC_KEY} true"
pause-legacy-testnet = "acton script --net testnet scripts/pause-legacy-contracts.tolk"

[import-mappings]
acton = ".acton"
contracts = "contracts"
gen = "gen"
tests = "tests"
wrappers = "wrappers"
